{
 "title": "Monitor",
 "description": "The monitor for variables",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT temperature\nFROM environment\nWHERE time > now() - interval '1 hour'\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "The temperature measured by the sensor",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  time,\n  temperature\nFROM\n  environment\nWHERE\n  time >= NOW() - INTERVAL '24 hours'\nORDER BY\n  time ASC;"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT humidity\nFROM environment\nWHERE time > now() - interval '1 hour'\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "The relative air humidity measured by the sensor",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  humidity\nFROM\n  environment\nWHERE\n  time >= NOW() - INTERVAL '24 hours'\nORDER BY\n  time ASC;"
    }
   ]
  }
 ]
}